# File: .github/workflows/workflow.yml

name: Run Azure Login with OIDC
on: [push]

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: 5c9d6817-a4c2-4afb-8dac-79e70d032a8d
          tenant-id: 5fd0f7e7-b27a-4b1d-9897-57500d767b01
          subscription-id: ae690070-fde1-463d-99e1-42c8a364ed7d
          allow-no-subscriptions: true

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
